---
- name: "Normalize block device path"
  set_fact:
    ek_block_device: "/dev/{{ ek_block_device }}"
  when:
  - '"/dev/" not in ek_block_device'

- name: "Create a {{ ek_fs_type }} filesystem on {{ ek_block_device }}"
  become: true
  filesystem:
    fstype: "{{ ek_fs_type }}"
    dev: "{{ ek_block_device }}"
    opts: -L "ek_{{ ek_mount_path | replace('/','_') }}"
    force: no

- name: "Get UUID for partition"
  become: true
  command: blkid -s UUID -o value {{ ek_block_device }}
  register: ek_part_uuid
  changed_when: false

- name: "Create mounting point {{ek_mount_path}}"
  become: true
  file:
    path: "{{ekara_fs_mount}}"
    state: directory
    mode: 0777

- name: "Mount {{ ek_block_device }} on {{ ek_mount_path }}"
  become: true
  mount:
    path: "{{ ek_mount_path }}"
    fstype: "{{ ek_fs_type }}"
    opts: "{{ ek_mount_opts }}"
    state: mounted
    src: 'UUID={{ ek_part_uuid.stdout }}'
