---
- name: "Normalize block device path"
  set_fact:
    ek_fs_device: "/dev/{{ ek_fs_device }}"
  when:
  - '"/dev/" not in ek_fs_device'

- name: "Create a {{ ek_fs_type }} filesystem on {{ ek_fs_device }}"
  become: true
  filesystem:
    fstype: "{{ ek_fs_type }}"
    dev: "{{ ek_fs_device }}"
    opts: -L "ek_{{ ek_fs_mount_path | replace('/','_') }}"
    force: no

- name: "Get UUID for partition"
  become: true
  command: blkid -s UUID -o value {{ ek_fs_device }}
  register: ek_part_uuid
  changed_when: false

- name: "Create mounting point {{ek_fs_mount_path}}"
  become: true
  file:
    path: "{{ek_fs_mount_path}}"
    state: directory

- name: "Mount {{ ek_fs_device }} on {{ ek_fs_mount_path }}"
  become: true
  mount:
    path: "{{ ek_fs_mount_path }}"
    opts: "{{ ek_fs_mount_opts }}"
    fstype: "{{ ek_fs_type }}"
    state: mounted
    src: 'UUID={{ ek_part_uuid.stdout }}'

- name: "Transfer ownership of mounting point {{ ek_fs_mount_path }} to {{ ek_fs_owner }}"
  when: ek_fs_owner is defined
  file:
    path: "{{ ek_fs_mount_path }}"
    owner: "{{ ek_fs_owner }}"
    state: directory
