---
# tasks file for ekara.filesytem
- name: Check FS name
  set_fact:
    ekara_fs_dev_format: "/dev/{{ekara_fs_dev}}"
  when: '"/dev/" not in ekara_fs_dev'
- name: Create a ext4 filesystem on "{{ekara_fs_dev}}"
  become: true
  filesystem:
    fstype: ext4
    dev: "{{ekara_fs_dev_format}}"

- name: Create mount point "{{ekara_fs_mount}}"
  become: true
  file:
    path: "{{ekara_fs_mount}}"
    state: directory
    mode: 0777

- name: Mount "{{ekara_fs_dev_format}}"
  become: true
  mount:
    path: "{{ekara_fs_mount}}"
    src: "{{ekara_fs_dev_format}}"
    fstype: ext4
    opts: defaults,nofail
    state: mounted
